name: Docker CI

on:
  push:
    branches: [ railway ]
  pull_request:
    branches: [ railway ]

jobs:

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - name: Building Frontend...
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Deploying Frontend...
        uses: actions/checkout@v4
      - uses: bervProject/railway-deploy@0.1.2-beta
        with:
          service: "f2f989ba-b7a1-4fd4-bc8f-bb401b794eed"
          railway_token: ${{ secrets.RAILWAY_TOKEN }}

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
          build-root-directory: backend/

  test-backend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Test with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: test
          build-root-directory: backend/

  deploy-backend:
    runs-on: ubuntu-latest
    needs: test-backend

    steps:
      - name: Deploying Backend...
        uses: actions/checkout@v4
      - uses: bervProject/railway-deploy@0.1.2-beta
        with:
          service: "edf919af-c1d4-460d-acc2-50ccc1264a5e"
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
